let data_doodle = [
  "porta-aviões",
  "avião",
  "despertador",
  "ambulância",
  "anjo",
  "migração animal",
  "formiga",
  "bigorna",
  "maçã",
  "braço",
  "aspargos",
  "machado",
  "mochila",
  "banana",
  "bandagem",
  "celeiro",
  "beisebol",
  "taco de beisebol",
  "cesta",
  "basquete",
  "morcego",
  "banheira",
  "praia",
  " urso",
  "barba",
  "cama",
  "abelha",
  "cinto",
  "banco",
  "bicicleta",
  "binóculos",
  "pássaro",
  "bolo de aniversário",
  "amora",
  "mirtilo",
  "livro ",
  "bumerangue",
  "tampa de garrafa",
  "gravata borboleta",
  "pulseira",
  "cérebro",
  "pão",
  "ponte",
  "brócolis",
  "vassoura",
  "balde",
  "escavadeira",
  "ônibus",
  "arbusto",
  "borboleta",
  "cacto",
  "bolo",
  "calculadora",
  "calendário",
  "camelo",
  "câmera",
  "camuflagem",
  "fogueira",
  "vela",
  "canhão",
  "canoa ",
  "carro",
  "cenoura",
  "castelo",
  "gato",
  "ventilador de teto",
  "violoncelo",
  "celular",
  "cadeira",
  "lustre",
  "igreja",
  "círculo",
  "clarinete ",
  "relógio",
  "nuvem",
  "xícara de café",
  "bússola",
  "computador",
  "biscoito",
  "cooler",
  "sofá",
  "vaca",
  "caranguejo",
  "giz de cera",
  "crocodilo",
  "coroa",
  "navio de cruzeiro",
  "copo",
  "diamante",
  "máquina de lavar louça",
  "prancha de mergulho",
  "cachorro",
  "golfinho",
  "donut",
  "porta",
  "dragão",
  "cômoda",
  "broca",
  "bateria",
  "pato",
  "haltere",
  "orelha",
  "cotovelo",
  "elefante",
  "envelope",
  "borracha",
  "olho",
  "óculos",
  "rosto",
  " ventilador",
  "pena",
  "cerca",
  "dedo",
  "hidrante",
  "lareira",
  "caminhão de bombeiros",
  "peixe",
  "flamingo",
  "lanterna",
  "chinelos",
  "lâmpada de chão",
  "flor",
  "disco voador",
  "pé",
  "garfo",
  "sapo",
  "frigideira",
  "jardim",
  "mangueira de jardim",
  "girafa",
  "cavanhaque",
  "clube de golfe",
  "uvas ",
  "grama",
  "guitarra",
  "hambúrguer",
  "martelo",
  "mão",
  "harpa",
  "chapéu",
  "fones de ouvido",
  "ouriço",
  "helicóptero",
  "capacete",
  "hexágono",
  "disco de hóquei",
  "taco de hóquei",
  "cavalo",
  "hospital",
  "balão de ar quente",
  "cachorro-quente",
  "banheira de hidromassagem",
  "ampulheta",
  "casa",
  "planta de casa",
  "furacão",
  "sorvete",
  "jaqueta",
  "prisão",
  "canguru",
  "chave",
  "teclado",
  "joelho",
  "faca",
  "escada",
  "lanterna",
  "laptop",
  "folha",
  "perna",
  "lâmpada",
  "isqueiro",
  "farol",
  "relâmpago",
  "linha",
  "leão",
  "batom",
  "lagosta",
  "pirulito",
  "caixa de correio",
  "mapa",
  " marcador",
  "correspondências",
  "megafone",
  "sereia",
  "microfone",
  "microondas",
  "macaco",
  "lua",
  "mosquito",
  "moto",
  "montanha",
  "rato",
  "bigode",
  "boca",
  "caneca",
  "cogumelo",
  "prego",
  "colar",
  "nariz",
  "oceano",
  "octógono",
  "polvo",
  "cebola",
  "forno",
  "coruja",
  " pincel",
  "lata de tinta",
  "palmeira",
  "panda",
  "calças",
  "clipe de papel",
  "pára-quedas",
  "papagaio",
  "passaporte",
  "amendoim",
  "pêra",
  "ervilhas",
  "lápis",
  "pinguim",
  "piano",
  "caminhão",
  "porta-retrato",
  "porco",
  "travesseiro",
  "abacaxi",
  "pizza",
  "alicate",
  "carro de polícia",
  "lagoa",
  "piscina",
  "picolé",
  "cartão postal",
  "batata",
  "tomada",
  "bolsa",
  "coelho",
  "guaxinim",
  "rádio",
  "chuva",
  "arco-íris",
  "ancinho",
  "controle remoto",
  "rinoceronte",
  "rifle",
  "rio",
  "montanha-russa",
  "patins",
  "veleiro",
  "sanduíche",
  "serra",
  "saxofone",
  "ônibus escolar",
  "tesoura",
  "escorpião",
  "chave de fenda",
  "tartaruga marinha",
  "balanço",
  "tubarão",
  "ovelha",
  "sapato",
  "shorts",
  "pá",
  "pia",
  "skate",
  "caveira",
  "arranha-céu",
  "saco de dormir",
  "carinha sorridente",
  "caracol",
  "cobra",
  "snorkel",
  "floco de neve",
  "boneco de neve",
  "bola de futebol",
  "meia",
  "lancha",
  "aranha ",
  "colher",
  "planilha",
  "quadrado",
  "rabisco",
  "esquilo",
  "escadas",
  "estrela",
  "bife",
  "estéreo",
  "estetoscópio",
  "pontos",
  "sinal de parada",
  "fogão",
  "morango",
  "streetlight",
  "feijão",
  "submarino",
  "mala",
  "sol",
  "cisne",
  "suéter",
  "balanço",
  "espada",
  "seringa",
  "mesa",
  "bule",
  "ursinho de pelúcia",
  "telefone",
  "televisão",
  "raquete de tênis",
  "tenda",
  "A Torre Eiffel",
  "A Grande Muralha da China",
  "A Mona Lisa",
  "tigre",
  "torradeira",
  "dedo do pé",
  "banheiro",
  "dente",
  "escova de dentes",
  "pasta de dente",
  "tornado",
  "trator",
  "semáforo",
  "trem",
  "árvore",
  "triângulo",
  "trombone",
  "caminhão",
  "trompete",
  "tshirt",
  "guarda-chuva",
  "roupa íntima",
  "van",
  "vaso",
  "violino",
  "máquina de lavar",
  "melancia",
  " toboágua",
  "baleia",
  "roda",
  "moinho de vento",
  "garrafa de vinho",
  "copo de vinho",
  "relógio de pulso",
  "ioga",
  "zebra",
  "ziguezague",
];

let dados_doodle = [
  "aircraft carrier",
  "airplane",
  "alarm clock",
  "ambulance",
  "angel",
  "animal migration",
  "ant",
  "anvil",
  "apple",
  "arm",
  "asparagus",
  "axe",
  "backpack",
  "banana",
  "bandage",
  "barn",
  "baseball",
  "baseball bat",
  "basket",
  "basketball",
  "bat",
  "bathtub",
  "beach",
  "bear",
  "beard",
  "bed",
  "bee",
  "belt",
  "bench",
  "bicycle",
  "binoculars",
  "bird",
  "birthday cake",
  "blackberry",
  "blueberry",
  "book",
  "boomerang",
  "bottlecap",
  "bowtie",
  "bracelet",
  "brain",
  "bread",
  "bridge",
  "broccoli",
  "broom",
  "bucket",
  "bulldozer",
  "bus",
  "bush",
  "butterfly",
  "cactus",
  "cake",
  "calculator",
  "calendar",
  "camel",
  "camera",
  "camouflage",
  "campfire",
  "candle",
  "cannon",
  "canoe",
  "car",
  "carrot",
  "castle",
  "cat",
  "ceiling fan",
  "cello",
  "cell phone",
  "chair",
  "chandelier",
  "church",
  "circle",
  "clarinet",
  "clock",
  "cloud",
  "coffee cup",
  "compass",
  "computer",
  "cookie",
  "cooler",
  "couch",
  "cow",
  "crab",
  "crayon",
  "crocodile",
  "crown",
  "cruise ship",
  "cup",
  "diamond",
  "dishwasher",
  "diving board",
  "dog",
  "dolphin",
  "donut",
  "door",
  "dragon",
  "dresser",
  "drill",
  "drums",
  "duck",
  "dumbbell",
  "ear",
  "elbow",
  "elephant",
  "envelope",
  "eraser",
  "eye",
  "eyeglasses",
  "face",
  "fan",
  "feather",
  "fence",
  "finger",
  "fire hydrant",
  "fireplace",
  "firetruck",
  "fish",
  "flamingo",
  "flashlight",
  "flip flops",
  "floor lamp",
  "flower",
  "flying saucer",
  "foot",
  "fork",
  "frog",
  "frying pan",
  "garden",
  "garden hose",
  "giraffe",
  "goatee",
  "golf club",
  "grapes",
  "grass",
  "guitar",
  "hamburger",
  "hammer",
  "hand",
  "harp",
  "hat",
  "headphones",
  "hedgehog",
  "helicopter",
  "helmet",
  "hexagon",
  "hockey puck",
  "hockey stick",
  "horse",
  "hospital",
  "hot air balloon",
  "hot dog",
  "hot tub",
  "hourglass",
  "house",
  "house plant",
  "hurricane",
  "ice cream",
  "jacket",
  "jail",
  "kangaroo",
  "key",
  "keyboard",
  "knee",
  "knife",
  "ladder",
  "lantern",
  "laptop",
  "leaf",
  "leg",
  "light bulb",
  "lighter",
  "lighthouse",
  "lightning",
  "line",
  "lion",
  "lipstick",
  "lobster",
  "lollipop",
  "mailbox",
  "map",
  "marker",
  "matches",
  "megaphone",
  "mermaid",
  "microphone",
  "microwave",
  "monkey",
  "moon",
  "mosquito",
  "motorbike",
  "mountain",
  "mouse",
  "moustache",
  "mouth",
  "mug",
  "mushroom",
  "nail",
  "necklace",
  "nose",
  "ocean",
  "octagon",
  "octopus",
  "onion",
  "oven",
  "owl",
  "paintbrush",
  "paint can",
  "palm tree",
  "panda",
  "pants",
  "paper clip",
  "parachute",
  "parrot",
  "passport",
  "peanut",
  "pear",
  "peas",
  "pencil",
  "penguin",
  "piano",
  "pickup truck",
  "picture frame",
  "pig",
  "pillow",
  "pineapple",
  "pizza",
  "pliers",
  "police car",
  "pond",
  "pool",
  "popsicle",
  "postcard",
  "potato",
  "power outlet",
  "purse",
  "rabbit",
  "raccoon",
  "radio",
  "rain",
  "rainbow",
  "rake",
  "remote control",
  "rhinoceros",
  "rifle",
  "river",
  "roller coaster",
  "rollerskates",
  "sailboat",
  "sandwich",
  "saw",
  "saxophone",
  "school bus",
  "scissors",
  "scorpion",
  "screwdriver",
  "sea turtle",
  "see saw",
  "shark",
  "sheep",
  "shoe",
  "shorts",
  "shovel",
  "sink",
  "skateboard",
  "skull",
  "skyscraper",
  "sleeping bag",
  "smiley face",
  "snail",
  "snake",
  "snorkel",
  "snowflake",
  "snowman",
  "soccer ball",
  "sock",
  "speedboat",
  "spider",
  "spoon",
  "spreadsheet",
  "square",
  "squiggle",
  "squirrel",
  "stairs",
  "star",
  "steak",
  "stereo",
  "stethoscope",
  "stitches",
  "stop sign",
  "stove",
  "strawberry",
  "streetlight",
  "string bean",
  "submarine",
  "suitcase",
  "sun",
  "swan",
  "sweater",
  "swingset",
  "sword",
  "syringe",
  "table",
  "teapot",
  "teddy-bear",
  "telephone",
  "television",
  "tennis racquet",
  "tent",
  "The Eiffel Tower",
  "The Great Wall of China",
  "The Mona Lisa",
  "tiger",
  "toaster",
  "toe",
  "toilet",
  "tooth",
  "toothbrush",
  "toothpaste",
  "tornado",
  "tractor",
  "traffic light",
  "train",
  "tree",
  "triangle",
  "trombone",
  "truck",
  "trumpet",
  "tshirt",
  "umbrella",
  "underwear",
  "van",
  "vase",
  "violin",
  "washing machine",
  "watermelon",
  "waterslide",
  "whale",
  "wheel",
  "windmill",
  "wine bottle",
  "wine glass",
  "wristwatch",
  "yoga",
  "zebra",
  "zigzag",
];

let numeroaleatorio = Math.floor(Math.random() * data_doodle.length + 1);

desafio = dados_doodle[numeroaleatorio];
document.getElementById("desafio").innerHTML = "tente desenhar " + desafio;

function carregamentoCanvas() {
  background("white");
  let numeroaleatorio2 = Math.floor(Math.random() * data_doodle.length + 1);
  desafio = dados_doodle[numeroaleatorio2];
  document.getElementById("desafio").innerHTML = "tente desenhar " + desafio;
  desafio2 = data_doodle[numeroaleatorio];
}

function preload() {
  classificacao = ml5.imageClassifier(DoodleNet);
}

function setup() {
  canvas = createCanvas(400, 400);
  canvas.center();
  background("white");
  canvas.mouseReleased(classificarRascunho);
}

function draw() {
  strokeWeight(4);
  stroke(0);
  color("black");
  if (mouseIsPressed) {
    line(mouseXfinal, mouseYfinal, mouseX, mouseY);
  }
  verificarRascunho();
  if (rascunhoDesenhado == desafio2) {
    rascunhoCorreto = "feito";
    pontos++;
    document.getElementById("pontos").innerHTML = "Pontuação:" + pontos;
  }
}

function classificarRascunho() {
  classificacao.classify(canvas, gotResults);
}

function gotResults() {
  if (error) {
    console.log(error);
  } else {
    console.log(results);
    rascunhoDesenhado = results[0].label;
    document.getElementById("legenda").innerHTML =
      "Seu Rascunho:" + rascunhoDesenhado;
    document.getElementById("precisão").innerHTML =
      "Precisão:" + Math.round(results[0].confidence * 100);
  }
}

let timer = 0;
let verificarTempo = "";

function verificarRascunho() {
  timer++;
  document.getElementById("tempo").innerHTML = "Tempo:" + timer;
  if (timer > 600) {
    timer = 0;
    verificarTempo = "completo";
  }
  if (verificarTempo == "completo") {
    verificarTempo = "";
    //rascunhoDesenhado = "";
    rascunhoCorreto = "";
    carregamentoCanvas();
  }
}
